# folder where the data is downloaded
data_root: ./data/ScanNet++

splits: [nvs_sem_train, nvs_sem_val]

scene_ids: [8b5caf3398, b20a261fdf]

# The following paths should be given relative to the DATA_ROOT/dslr/
# If not given, will use the default directory defined in ScannetppScene class

# input_image_dir: resized_images
# input_mask_dir: resized_anon_masks
# input_transforms_path: nerfstudio/transforms.json
input_depth_dir: render_depth

# All use the relative path to DATA_ROOT/dslr/
out_image_dir: undistorted_images
out_mask_dir: undistorted_anon_masks
out_depth_dir: undistorted_depths
out_transforms_path: nerfstudio/transforms_undistorted.json
